#!/usr/bin/env node

/**
 * Accuracy Report Generator
 *
 * Reads Vitest JSON output from stdin and produces a markdown accuracy report.
 *
 * Usage:
 *   npx vitest run --config vitest.accuracy.config.ts --reporter=json 2>/dev/null | node scripts/accuracy-report.mjs
 *
 * Or via npm script:
 *   npm run test:accuracy:report
 */

import { readFileSync } from "node:fs";

let input = "";
try {
  input = readFileSync("/dev/stdin", "utf8");
} catch {
  console.error("No input on stdin. Run via: npm run test:accuracy:report");
  process.exit(1);
}

let report;
try {
  report = JSON.parse(input);
} catch {
  // If JSON parsing fails, just produce a summary from running the tests directly
  console.log("# Calcifer Accuracy Report");
  console.log(`\nGenerated: ${new Date().toISOString().split("T")[0]}`);
  console.log("\n> Run `npm run test:accuracy` for detailed test output.");
  console.log("\n## Note\n\nCould not parse JSON reporter output. Run with `--reporter=json` flag.");
  process.exit(0);
}

const testResults = report.testResults ?? [];
const now = new Date().toISOString().split("T")[0];

let totalTests = 0;
let totalPassing = 0;
let totalFailing = 0;

const sections = [];

for (const file of testResults) {
  const fileName = file.name?.split("/").pop() ?? "unknown";
  const sectionName = fileName.replace(".accuracy.ts", "").replace(/-/g, " ");

  const tests = file.assertionResults ?? [];
  const passing = tests.filter((t) => t.status === "passed").length;
  const failing = tests.filter((t) => t.status === "failed").length;

  totalTests += tests.length;
  totalPassing += passing;
  totalFailing += failing;

  const rows = tests.map((t) => {
    const status = t.status === "passed" ? "PASS" : "FAIL";
    const name = t.ancestorTitles?.join(" > ") + " > " + t.title;
    return `| ${name} | ${status} |`;
  });

  sections.push({
    name: sectionName,
    passing,
    failing,
    total: tests.length,
    rows,
  });
}

// Output markdown
console.log("# Calcifer Accuracy Report");
console.log(`\nGenerated: ${now}`);
console.log(`Engine: Calcifer FIRECALC`);
console.log(`Dataset: Shiller v1 (1871-01 to 2023-09, 1,833 monthly records)`);
console.log("");
console.log(`## Summary`);
console.log("");
console.log(`| Metric | Value |`);
console.log(`|--------|-------|`);
console.log(`| Total golden tests | **${totalTests}** |`);
console.log(`| Passing | **${totalPassing}** |`);
console.log(`| Failing | **${totalFailing}** |`);
console.log(`| Pass rate | **${totalTests > 0 ? ((totalPassing / totalTests) * 100).toFixed(1) : 0}%** |`);
console.log("");

for (const section of sections) {
  const icon = section.failing === 0 ? "✅" : "❌";
  console.log(`## ${icon} ${section.name} (${section.passing}/${section.total})`);
  console.log("");
  console.log("| Test | Status |");
  console.log("|------|--------|");
  for (const row of section.rows) {
    console.log(row);
  }
  console.log("");
}

console.log("---");
console.log(`\n*Report generated by \`scripts/accuracy-report.mjs\`. Run \`npm run test:accuracy:report\` to regenerate.*`);

if (totalFailing > 0) {
  process.exit(1);
}
